<a href="https://colab.research.google.com/github/WardTurkyeh/ML-py/blob/main/cross_val.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_iris

In [5]:
flowers = load_iris()
dir(flowers)

['DESCR', 'data', 'feature_names', 'filename', 'target', 'target_names']

In [6]:
from sklearn.model_selection import cross_val_score

In [15]:
lg_score = cross_val_score(LogisticRegression(), flowers.data, flowers.target)
lg_score

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [16]:
svm_scores = cross_val_score(SVC(), flowers.data, flowers.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [14]:
rfc_score = cross_val_score(RandomForestClassifier(n_estimators=40), flowers.data, flowers.target)
rfc_score

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])